name: Build and Deploy Singularity Image

on:
  workflow_dispatch:
    inputs:
      dockerhub-username:
        description: 'Dockerhub username'
        default: 'cuhkhaosun'
        required: true
        type: string
      image-name:
        description: 'Image name'
        default: 'base'
        required: true
        type: string
      image-tag:
        description: 'Image tag'
        default: 'latest'
        required: true
        type: string

jobs:
  build-singularity-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Pull Docker image and build Singularity image
        run: |
          singularity build ${{ inputs.image-name }}.sif docker://${{ inputs.dockerhub-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image-name }}-image-file
          path: ${{ inputs.image-name }}.sif
          compression-level: 0
